### PR TITLE
Added compile instructions for Linux

### PR DESCRIPTION
**Pull request by Vulldozer**
Added compile instructions for Linux, tested it on Ubuntu 20.04 LTS, should work on any Linux distro.

### CODE REVIEW

**Comment by Pedro-Beirao** [comment]
Thanks for the PR!

Does dsda-doom.wad and the binary need to be copied / symlinked before compiling? On MacOS it is needed so that it goes to the correct place of the App Bundle.

**Comment by Vulldozer** [comment]
I am not sure if dsda-doom.wad is necessary or not so I kept it in.

As for the binary, if the user compiles dsda-doom using the official instructions and with the 'make install' command ([see step 4](https://github.com/kraflab/dsda-doom/blob/master/prboom2/INSTALL)), then there is no need to symlink/copy as dsda-launcher will automatically detect the binary.

It is only necessary to symlink/copy it if the user has compiled dsda-doom but installed it manually (or kept it in the build folder) instead of using the makefile. (make install).

**Comment by Pedro-Beirao** [comment]
Make install should also put dsda-doom.wad on the correct place.

So there is no need to copy it before building the launcher.

Could you remove the point 3 and the screenshot of the folder? Other than that, everything looks fine.

**Comment by Vulldozer** [comment]
Sure I'll do that tomorrow and update the PR

**Comment by Vulldozer** [comment]
It should be all good now

**Comment by Pedro-Beirao** [comment]
Thanks!

**Pull request merged**
